name: Publish Packages
on:
  push:
    branches: [ "**" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build
      - name: upload
        uses: actions/upload-artifact@v3
        with:
         name: EcoEnchants
         path: build/libs/
